User.create(username: "WeRunThisPlace", password: "1234")
User.create(username: "HamSlayer", password: "4324")
User.create(username: "UpFan123", password: "uprules")
User.create(username: "RedSoxRulz1", password: "SOXfan3341")
Catergory.create(name: "General")
Catergory.create(name: "Suggestions")
Catergory.create(name: "Computer Components")
Catergory.create(name: "Share Videos")
Catergory.create(name: "Support")
Catergory.create(name: "Report Misconduct")
Post.create(user_id: 1, title:"The Decoding of Video Games", content: "The decoding of video games will forever be the work of dilligent and hard-working individuals.", category_id: 1)
Post.create(user_id: 3, title:"Video Games, and the Benifits", content: "Have you ever felt like a plastic bag drifting through the wind? Well than I don't think you've ever tried the thrill of video games!", category_id: 1)
Post.create(user_id: 4, title:"How MLB The Show Improved my Game", content: "I've been a baseball player since high school. I'm an avid sports watcher, but me and my buddies will go to the diamond every now and again. I have noticed that my batting average has increased %15 since playing MLB The Show 2019", category_id: 1)
Post.create(user_id: 2, title:"My first suggestion", content:"We should have a place to rant about the unfair conditions that developers leave the player in when they have zero customer support.", category_id: 2)
Post.create(user_id: 3, title:"My Suggestion to Make me admin", content: "I've been a part of this community for awhile now and I think I should be able to help with more things around here Contact me for my resume.", category_id: 2)
Post.create(user_id: 1, title:"Suggested", content: "MOAR Categories!", category_id: 2)
Reply.create(user_id: 3, message:"This is not a good idea.", post_id: 6)
Post.create(user_id: 4, title:"My new Ryzen 5 5600x", content: "I just purchased this cpu: https://www.bestbuy.com/site/amd-ryzen-5-5600x-4th-gen-6-core-12-threads-unlocked-desktop-processor-with-wraith-stealth-cooler/6438943.p?skuId=6438943&ref=212&loc=1&extStoreId=459&ref=212&loc=1&gclid=CjwKCAjw2ZaGBhBoEiwA8pfP_gDdB65UNTES30ZMfd4d5BeujTHPbKwV4HGe-IcScU9wyU3EEpTeXBoCx3oQAvD_BwE&gclsrc=aw.ds and I was wondering if anyone else has?", category_id: 3)
Post.create(user_id: 1, title:"I found this hilarious video about cats!", content: "https://www.youtube.com/watch?v=G8KpPw303PY", category_id: 4)
Post.create(user_id: 3, title:"I was wondering how to overclock", content: "I recently upgraded my CPU to Intel and I was wondering how to overclock the the fans", category_id: 5)
Post.create(user_id: 1, title:"UpFan123", content: "UpFan123 has been seen being rude to other users!", category_id: 6)
Post.create(user_id: 2, title:"Cooking Ham", content: "I was trying to cook ham with my CPU last night and my CPU isn't loving the honey glaze... any help?", category_id: 5)
Post.create(user_id: 2, title:"LMAO Look at this", content: "https://www.youtube.com/watch?v=SfLV8hD7zX4", category_id: 4)
Reply.create(user_id: 2, post_id: 1, message:"Wow thats super cool.")